config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home', as: 'home'
  get '/secret', to: 'static_pages#secret', as: 'secret'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
	resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save {self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}
	validates :password, confirmation: { case_sensitive: true }

	# Returns the hash digest of the given string.
 def User.digest(string)
	 cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	 BCrypt::Engine.cost
	 BCrypt::Password.create(string, cost: cost)
 end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to secret_path
      puts 'I AM IN'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to home_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_login, only: [:secret]

  def home
  end

  def secret
  end

  def require_login
    if logged_in?
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user?, only: [:edit]

  def index
  end

  def create
    @user = User.create(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      log_in @user
      redirect_to secret_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  def current_user?
    if current_user != nil || current_user.email != User.find(params[:id]).email
      redirect_to home_path
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #F9AB9F;">

  <div class="container">
    <nav>
      <ul class="nav navbar-light" style: >
       <li class="nav-item">
        <a class="nav-link" <%= link_to "Home", "/" %></a>
      </li>
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to " Secret ", secret_path %></a>
          </li>
          <li class="nav-item">
           <a class="nav-link"  <%= link_to " Profile ", current_user %></a>
         </li>
          <li class="nav-item">
           <a <%= link_to " Log out ", logout_path, method: :delete %> </a>  
         </li>
        <% else %>
          <li class="nav-item">
           <a class="nav-link"  <%= link_to " Log in ", login_path %></a>
         </li>
        <% end %>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Site De La Réponse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/header'%>
    <div class="container" style='padding-top: 40px' style='padding-left: 30px'>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur notre site topeeee secreeeeettt !!!</h1>
<p>Enregistre toi pour pouvoir acceder aux dossiers secrets de la NASA</p>
<%= link_to 'Enregistre-toi', new_user_path, class: "btn btn-lg btn-primary"%>

app/views/static_pages/secret.html.erb
<center><h1>La réponse à la question de l'univers est :</h1>
<h2>Ta mère !!!!!!!!</h2>
</center>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1><center><strong>REJOINS-NOUS !</strong></center></h1>
<%= form_for @user do |f| %>
  <div class='form-group'>
    <label><strong>Ton email</strong></label>
    <center><%= f.text_field :email, class: 'form-control', placeholder: 'toto@mail.com'%></center>
  </div>
  <div class='form-group'>
    <label><strong>Mot de Passe</strong></label>
    <center><%= f.text_field :password, class: 'form-control', placeholder: '*********'%></center>
  </div>
  <div class='form-group'>
    <label><strong>Confirmes ton mot de passe</strong></label>
    <center><%= f.text_field :password_confirmation, class: 'form-control', placeholder: '**********'%></center>
  </div>
  <center><button type='submit' class='btn btn-primary'><strong>Enregistrer</strong></button></center>  
<% end %>

app/views/users/show.html.erb
<h1>Profil</h1>
<p>Ceci est la page de <%= User.find(params[:id]).email%></p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>